export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
  INITIAL_REQUEST: "INITIAL_REQUEST",
  INITIAL_SUCCESS: "INITIAL_SUCCESS",
  INITIAL_FAILURE: "INITIAL_FAILURE",
};